

server:
  port: 8085

spring:
  datasource:
    password:
    username: sa
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/jpadata

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  logging.level:
    org.hibernate.SQL: debug